server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokedex
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  main:
    banner-mode: off
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

application:
  security:
    jwt:
      secret-key: s8GvnYNP7FJWtD4HCbX9nVxCG+G4CpJZZqPkBRINsLs=
      access-token-expiration: 1800000
      refresh-token-expiration: 60480000

